### PR TITLE
Cleaning up CI/CD

### PR DESCRIPTION
**Pull request by Hopeberg**
Cleanup of CI/CD:

Removed debugging steps 
Removed abundant and commented out code
Removed comments, but kept the links to documentation

### CODE REVIEW

**Comment by janlishak** [comment]
I'll check it out, and get back to you

**Comment by janlishak** [comment]
I created a new branch called tags-and-labels to show you how the meta action works. You can check the run history, if the image above doesn't work. The step name was undefined so the debug action didn't work but the labels were working alright , I set them up in a way that both images would have two tags. "latest" (so that it points to the newest version) and sha which is the commit sha so you can see which commit was the image built from) it's not as good as having version but at least you can tell by the commit sha exactly from which code it was built. (this would get lost by your changes)

It took me some time to understand the meta action. For that I had to check the documentation, It takes all the data from git it makes meaningful tags and labels. Labels are not mandatory but they are nice. For example it added the date and time when the image was created. (this would get lost by the changes) there are more labels like the repository and so on. I'd like to have that as it was. 

id_rsa, is as ambiguous as do_key or my_key, please change it to "terraform" coz thats the name of the key everywhere else in digital ocean, in github secrets and so on. 

yes, I agree to remove push: ${{ github.event_name != 'pull_request' }} 
also removing the signing code and some of the comments.

but I'd keep the links to documentation. It helped when I was changing the parameters. So I don't have to go look for it again in the future.

**Comment by Hopeberg** [comment]
Thanks Jan, I'll look into it tomorrow

**Comment by Hopeberg** [comment]
Thanks for your good suggestions. I have added extracting metadata and tags/labels back in, and also links to documentation. Will look at the branch you made tomorrow. Regarding the path to the private key ~/.ssh/id_rsa, do you suggest to change it to ~/.ssh/terraform?

**Comment by janlishak** [comment]
image

yes ~/.ssh/terraform sounds good.

**Comment by Hopeberg** [comment]
Looks cool, will play with it tomorrow :_)
Have changed the path to .ssh/terraform 
Good night!

**Comment by janlishak** [comment]
Hi, 
thank you for adding my suggestions. 🙂
I tried to run the pipeline manually and it seems there's some syntax error. 
I don't think we need the token-id, It was probably there for code signing which we don't use.
image

**Comment by Hopeberg** [comment]
Alright, will remove the id_token again

**Comment by janlishak** [comment]
* app image was not published, tags were added from steps.meta-api.outputs.tags (instead of steps.meta-app.outputs.tags)
* bumped all actions to newest versions

**Review by janlishak — APPROVED** [review]

**Pull request merged**
