### PR TITLE
Grafana

### PR DESCRIPTION
**Pull request by janlishak**
Co-authored by: Rasmus Nordbjærg
Co-authored by: Roman 
Co-authored by: Viktoria Hopeberg 
Co-authored by: ChatGPT 

don't merge yet

### CODE REVIEW

**Comment by janlishak** [comment]
dont' merge yet, pls

**Comment by janlishak** [comment]
I think is ready. It would be nice to have at least 2 approvals.

**Review by Hopeberg — DISMISSED** [review]

**Comment by janlishak** [comment]
thank @Romes8 for noticing the merge conflict
fixed

**Review by Romes8 — APPROVED** [review]
Good job. Lets try it.

**Review by Hopeberg — APPROVED** [review]

**Pull request merged**
