### PR TITLE
Add workflow for PDF generation

### PR DESCRIPTION
**Pull request by danielgron**
Runs workflow when changes happen in /report folder
Creates PDF from md files in report sorted by name and outputs one pdf.

Coauthor - ChatGPT

### CODE REVIEW

**Review by rasmus-bn — COMMENTED** [review]
Looks good!
Could this cause the workflow to trigger itself endlessly? 🤔

**Comment by danielgron** [comment]
> Looks good! Could this cause the workflow to trigger itself endlessly? 🤔

image

It doesn't do that in my forked repo. But I hadn't thought about that.

It's a case of "It works, but I don't know why"

**Comment by rasmus-bn** [comment]
> > Looks good! Could this cause the workflow to trigger itself endlessly? 🤔
> 
> image
> 
> It doesn't do that in my forked repo. But I hadn't thought about that.
> 
> It's a case of "It works, but I don't know why"

Good enough for me! I guess the PDF stays the same if the readmes are unchanged

**Review by rasmus-bn — APPROVED** [review]
Approved

**Pull request merged**
